### PR TITLE
Allow "real" ec2 region name to be used as ses_region

### PR DESCRIPTION
**Pull request by robinbowes**
eg. 'us-east-1' and 'US EAST' are equivalent.

### CODE REVIEW

**Comment by Conzar** [comment]
I think this might be confusing to the user.  Amazon SES only offers 3 [regions](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html) which are

* us-east-1
* us-west-2
* eu-west-1

Allowing the user to specify us-west-1 for instance, actually doesn't give the user the "1" availability zone.  Likewise, allowing the user to specify eu-central-1 doesn't give the user the eu-central region.

I think maybe the readme should be updated instead to clarify how regions and availability zones work.

**Comment by robinbowes** [comment]
The idea behind my change was to allow the user to specify the region in which the instance is based and the module would choose the appropriate SES instance to use. So, if you want to use SES in us-west-1 then the module would use the nearest SES region which would be us-west-2.

If the user wants to specify an explicit SES region they can do this by using "US EAST", "US WEST" or "EU".

**Comment by Conzar** [comment]
I have updated the readme with more clarification of the ses_region.  Could you provide a use case or 2 where a user would say for instance specify eu-central-1?

**Comment by robinbowes** [comment]
The main use-case I had in mind when coding this was my own. Our nodes use a custom fact that returns the region in which the node is running:
```
# facter -p whatami_region
us-east-1
```
I wanted to be able to use that directly in the amazon_ses class declaration, eg:
```
  class{'::amazon_ses':
    domain          => $::domain,
    smtp_username   => $smtp_username,
    smtp_password   => $smtp_password,
    ses_region      => $::whatami_region,
    inet_interfaces => 'localhost',
    inet_protocols  => 'ipv4',
  }
```
Without the changes in this PR I would need to do additional work to determine what to pass to ses_region. ie. either some conditional logic in the class using amazon_ses, or add a value to the region-specific level of my hiera hierarchy.

**Comment by Conzar** [comment]
Sounds like a legitimate use case.  I will include these changes this week.

**Pull request merged**
